name = "FiniteVarietiesDB"
uuid = "30c72606-59d1-47a9-b9ee-5125b74b420d"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
DBInterface = "2.6.1"
DataFrames = "1.8.1"
DuckDB = "1.4.1"
